### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by miraixyz** [jkwill87/stonky#16]
--------------------------------- environment ----------------------------------

 - date = 2022-01-15
 - platform = Linux-5.10.63-v7+-armv7l-with-glibc2.31
 - arguments = []
 - python version = 3.9.2
 - stonky version = 1.4.0
 - teletype version = 1.1.0

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/stonky/__main__.py", line 12, in entrypoint
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/stonky/__main__.py", line 32, in main
    await tty.draw()
  File "/usr/local/lib/python3.9/dist-packages/stonky/tty.py", line 115, in draw
    print("\n".join(lines))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u25bc' in position 51: ordinal not in range(256)

=============================== CRASH REPORT END ===============================

Dang, it looks like stonky crashed! Please consider filling an issue at
https://github.com/jkwill87/stonky/issues along with this report.

**Comment by miraixyz** [comment]
Was able to solve issue by using the following line in terminal:

export PYTHONIOENCODING=utf8

thanks
