### ISSUE TITLE
Mutual Funds Error

### ISSUE THREAD

**Issue by billdriver** [jkwill87/stonky#2]
There appears to be some issue when pulling Mutual Fund information. I tried the follow 3 Mutual Funds (HBLFX, JSGTX, JNBZX) and received an error, listed below. I validated that all 3 are available in the Yahoo Finance site. All other stocks I entered work perfectly fine. 

============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2020-07-25
 - platform = Windows-10-10.0.18362-SP0
 - arguments = []
 - python version = 3.8.5
 - stonky version = 1.0.1
 - teletype version = 1.1.0

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "C:\Users\user1\AppData\Roaming\Python\Python38\site-packages\stonky\__main__.py", line 12, in main
    stock_store = StockStore(api, settings)
  File "C:\Users\user1\AppData\Roaming\Python\Python38\site-packages\stonky\stock_store.py", line 15, in __init__
    self.update_stocks()
  File "C:\Users\user1\AppData\Roaming\Python\Python38\site-packages\stonky\stock_store.py", line 27, in update_stocks
    self._stocks = {
  File "C:\Users\user1\AppData\Roaming\Python\Python38\site-packages\stonky\stock_store.py", line 28, in <dictcomp>
    ticket: self.api.get_quote(ticket)
  File "C:\Users\user1\AppData\Roaming\Python\Python38\site-packages\stonky\api.py", line 28, in get_quote
    volume=summary_data["volume"]["raw"],
KeyError: 'raw'

=============================== CRASH REPORT END ===============================

**Comment by jkwill87** [comment]
Yep, should easily be fixable, thanks!

**Comment by jkwill87** [comment]
Should be fixed in v1.1.0
